const defaultResponseMessage = {
  100: "Continue",
  101: "Switching Protocols",
  102: "Processing",
  103: "Early Hints",
  200: "Success!",
  201: "Created",
  202: "Accepted",
  203: "Non-Authoritative Information",
  204: "No Content",
  205: "Reset Content",
  206: "Partial Content",
  207: "Multi-Status",
  208: "Already Reported",
  226: "IM Used",
  300: "Multiple Choices",
  301: "Moved Permanently",
  302: "Found",
  303: "See Other",
  304: "Not Modified",
  305: "Use Proxy",
  307: "Temporary Redirect",
  308: "Permanent Redirect",
  400: "Bad Request",
  401: "Unauthorized",
  402: "Payment Required",
  403: "Forbidden",
  404: "Not Found",
  405: "Method Not Allowed",
  406: "Not Acceptable",
  407: "Proxy Authentication Required",
  408: "Request Timeout",
  409: "Conflict",
  410: "Gone",
  411: "Length Required",
  412: "Precondition Failed",
  413: "Payload Too Large",
  414: "URI Too Long",
  415: "Unsupported Media Type",
  416: "Range Not Satisfiable",
  417: "Expectation Failed",
  418: "I'm a Teapot",
  421: "Misdirected Request",
  422: "Unprocessable Entity",
  423: "Locked",
  424: "Failed Dependency",
  425: "Too Early",
  426: "Upgrade Required",
  428: "Precondition Required",
  429: "Too Many Requests",
  431: "Request Header Fields Too Large",
  451: "Unavailable For Legal Reasons",
  500: "Internal Server Error",
  501: "Not Implemented",
  502: "Bad Gateway",
  503: "Service Unavailable",
  504: "Gateway Timeout",
  505: "HTTP Version Not Supported",
  506: "Variant Also Negotiates",
  507: "Insufficient Storage",
  508: "Loop Detected",
  510: "Not Extended",
  511: "Network Authentication Required",
};
const successCode = new Set([200, 201, 202, 203, 204, 205, 206, 207, 208, 226]);
const months = [
  { name: "January", short: "Jan" },
  { name: "February", short: "Feb" },
  { name: "March", short: "Mar" },
  { name: "April", short: "Apr" },
  { name: "May", short: "May" },
  { name: "June", short: "Jun" },
  { name: "July", short: "Jul" },
  { name: "August", short: "Aug" },
  { name: "September", short: "Sep" },
  { name: "October", short: "Oct" },
  { name: "November", short: "Nov" },
  { name: "December", short: "Dec" },
];
const genres = [
  { label: "Rock", value: "Rock" },
  { label: "Pop", value: "Pop" },
  { label: "Hip Hop", value: "Hip Hop" },
  { label: "Jazz", value: "Jazz" },
  { label: "Blues", value: "Blues" },
  { label: "Country", value: "Country" },
  { label: "Electronic", value: "Electronic" },
  { label: "R&B", value: "R&B" },
  { label: "Reggae", value: "Reggae" },
  { label: "Classical", value: "Classical" },
  { label: "Folk", value: "Folk" },
  { label: "Metal", value: "Metal" },
  { label: "Punk", value: "Punk" },
  { label: "Funk", value: "Funk" },
  { label: "Soul", value: "Soul" },
  { label: "Gospel", value: "Gospel" },
  { label: "Alternative", value: "Alternative" },
  { label: "Indie", value: "Indie" },
  { label: "Dance", value: "Dance" },
  { label: "Disco", value: "Disco" },
  { label: "Latin", value: "Latin" },
  { label: "Ska", value: "Ska" },
  { label: "Rap", value: "Rap" },
  { label: "World", value: "World" },
  { label: "New Age", value: "New Age" },
  { label: "Gospel", value: "Gospel" },
  { label: "Ambient", value: "Ambient" },
  { label: "Experimental", value: "Experimental" },
  { label: "Instrumental", value: "Instrumental" },
  { label: "Opera", value: "Opera" },
];

module.exports = {
  defaultResponseMessage,
  successCode,
  months,
  genres,
};
